### ISSUE TITLE
execinfo.h does not exist in alpine linux 3.19

### ISSUE THREAD

**Issue by mf01** [X-Ryl669/eMQTT5#14]
execinfo.h does not exist in alpine linux 3.19

Hence, in Types.hpp the #include <execinfo.h> could not be found. Is it possible to keep this optionally?

**Comment by X-Ryl669** [comment]
Sure. This is not required, since eMQTT5 doesn't include backtracing helpers. I've fixed it in #15. Let me know if it's ok for you.

**Comment by mf01** [comment]
yes, works for me.
