### ISSUE TITLE
Linux specific int types

### ISSUE THREAD

**Issue by mf01** [X-Ryl669/eMQTT5#18]
in LinuxSpecific.cpp [0] I have to change the typedef, otherwise it will not compile:

```
    typedef uint32_t __u32;         /* hack to avoid including kernel header in userspace */
    typedef uint16_t __u16;         /* ditto */
    typedef uint8_t __u8;           /* ditto */
    // For camir version of #include <linux/ethtool.h>
    typedef uint32_t  u32;            /* hack to avoid including kernel header in userspace */
    typedef uint16_t  u16;            /* ditto */
    typedef uint8_t   u8;             /* ditto */
    typedef uint64_t  u64;            /* ditto */
```

[0] https://github.com/X-Ryl669/eMQTT5/blob/e54342c4b59a052ea5ca317eeab8b57fb854e648/tests/ClassPath/src/LinuxSpecific.cpp#L11

**Comment by X-Ryl669** [comment]
I'm developing on Linux and I had no issue so far with any kernel version from 3.0 to 6.5. 

Can you be more specific about the error message ?
What is the platform you're building on, is it linux, 32bits ? 64bits? cross-compiler? and what version?
