### ISSUE TITLE
Why there is no release version ?

### ISSUE THREAD

**Issue by Singa17** [X-Ryl669/eMQTT5#21]
Hi,
This repo is active for long time but why there is no release version?

**Comment by X-Ryl669** [comment]
Well, I never needed to make one. It's been used in my products as a rolling release for years without major issue. 

I'll try to look for building a release CI pipeline so at least when there is a slow development time, it'll make a release by itself.

**Comment by X-Ryl669** [comment]
I've created a release candidate on the main page. It's open for 2 weeks and then I'll release the version 1.0.
Starting from 1.0, we'll rework the publish cycle to try to remove the actual drawback of the current system, so it'll somehow break the current behavior of the code.

**Comment by X-Ryl669** [comment]
v1.0.0 was published. It contains the latest bugfixes. Work has begun on v2.
