### ISSUE TITLE
How to connect without ClientID?

### ISSUE THREAD

**Issue by 1115william** [X-Ryl669/eMQTT5#22]
It needs a clientID to initialize the Network::Client::MQTTv5, but if we don't have clientID, how to connect to the server? for example, connect to a remote broker.

**Comment by X-Ryl669** [comment]
That's not a problem. You can pass a NULL (nullptr or 0) value for the clientID in the constructor and it'll just use what the broker provides.

The documentation in the MQTTClient.hpp states:
```cpp
@param clientID     A client identifier if you need to provide one. If empty or null, the broker will assign one
```
I'm not building the doxygen documentation by default when you build the library, so you might miss it. 

In that case, I invite you to [visit the documentation size](https://blog.cyril.by/en/documentation/emqtt5-doc/emqtt5) for a better description of parameters and what is supported.
