### ISSUE TITLE
eMQTT5 does not install at all

### ISSUE THREAD

**Issue by wrmbaron** [X-Ryl669/eMQTT5#3]
Hi, it's me again :laughing:,

when including eMQTT5 into some project, which wants to install eMQTT5 along with some other product, at least the shared object should be installed, possibly even the test program. Using eMQTT5 without local modifications will lead to the effect, that the installed product will not have eMQTT5 installed. CMake before version 3.13 will not allow this to be added from the outside, so could you please add something like

    install(TARGETS eMQTT5 LIBRARY DESTINATION lib)

and

    install(TARGETS MQTTc RUNTIME DESTINATION bin)

to the respective project files?

**Comment by X-Ryl669** [comment]
Should be done now. Please report if it fails.
